// Server-side teams data (without image imports)
export const TEAMS_DATA = [
  {
    id: 'flamengo',
    name: 'Flamengo',
    shortName: 'FLA',
    logoUrl: 'https://logodetimes.com/flamengo.png',
    primaryColor: '#E31E24',
    secondaryColor: '#000000',
  },
  {
    id: 'palmeiras',
    name: 'Palmeiras',
    shortName: 'PAL',
    logoUrl: 'https://logodetimes.com/palmeiras.png',
    primaryColor: '#006437',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'corinthians',
    name: 'Corinthians',
    shortName: 'COR',
    logoUrl: 'https://logodetimes.com/corinthians.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    shortName: 'SAO',
    logoUrl: 'https://logodetimes.com/saopaulo.png',
    primaryColor: '#E31E24',
    secondaryColor: '#000000',
  },
  {
    id: 'santos',
    name: 'Santos',
    shortName: 'SAN',
    logoUrl: 'https://logodetimes.com/santos.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'gremio',
    name: 'Grêmio',
    shortName: 'GRE',
    logoUrl: 'https://logodetimes.com/gremio.png',
    primaryColor: '#0083CA',
    secondaryColor: '#000000',
  },
  {
    id: 'internacional',
    name: 'Internacional',
    shortName: 'INT',
    logoUrl: 'https://logodetimes.com/internacional.png',
    primaryColor: '#E5001B',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'atletico-mg',
    name: 'Atlético Mineiro',
    shortName: 'CAM',
    logoUrl: 'https://logodetimes.com/atletico-mg.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'cruzeiro',
    name: 'Cruzeiro',
    shortName: 'CRU',
    logoUrl: 'https://logodetimes.com/cruzeiro.png',
    primaryColor: '#003DA5',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'botafogo',
    name: 'Botafogo',
    shortName: 'BOT',
    logoUrl: 'https://logodetimes.com/botafogo.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'fluminense',
    name: 'Fluminense',
    shortName: 'FLU',
    logoUrl: 'https://logodetimes.com/fluminense.png',
    primaryColor: '#7B1045',
    secondaryColor: '#006437',
  },
  {
    id: 'vasco',
    name: 'Vasco da Gama',
    shortName: 'VAS',
    logoUrl: 'https://logodetimes.com/vasco.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'atletico-pr',
    name: 'Athletico Paranaense',
    shortName: 'CAP',
    logoUrl: 'https://logodetimes.com/atletico-pr.png',
    primaryColor: '#E31E24',
    secondaryColor: '#000000',
  },
  {
    id: 'bahia',
    name: 'Bahia',
    shortName: 'BAH',
    logoUrl: 'https://logodetimes.com/bahia.png',
    primaryColor: '#0047AB',
    secondaryColor: '#E31E24',
  },
  {
    id: 'fortaleza',
    name: 'Fortaleza',
    shortName: 'FOR',
    logoUrl: 'https://logodetimes.com/fortaleza.png',
    primaryColor: '#003DA5',
    secondaryColor: '#E31E24',
  },
  {
    id: 'bragantino',
    name: 'Red Bull Bragantino',
    shortName: 'RBB',
    logoUrl: 'https://logodetimes.com/bragantino.png',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
  },
  {
    id: 'cuiaba',
    name: 'Cuiabá',
    shortName: 'CUI',
    logoUrl: 'https://logodetimes.com/cuiaba.png',
    primaryColor: '#FFD700',
    secondaryColor: '#006400',
  },
  {
    id: 'goias',
    name: 'Goiás',
    shortName: 'GOI',
    logoUrl: 'https://logodetimes.com/goias.png',
    primaryColor: '#006437',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'ceara',
    name: 'Ceará',
    shortName: 'CEA',
    logoUrl: 'https://logodetimes.com/ceara.png',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'sport',
    name: 'Sport Recife',
    shortName: 'SPT',
    logoUrl: 'https://logodetimes.com/sport.png',
    primaryColor: '#E31E24',
    secondaryColor: '#000000',
  },
];
